### ISSUE TITLE
V3 upgraded. Is this anything? ⇾ WARNING:waitress.queue:Task queue depth is 55

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#108]
So I left the v3 migration overnight, and it has completed, with a few warnings...GUI is acting strange, in that it's constantly updating with the page refreshing.

```
[thirdparty] Got track image for (['The Chainsmokers'], 'High') from LastFM
[dbcache] Cache Size: 6081 [23734 E], System RAM Utilization: 68.8%, Cache Hits: 32542/52129
[sqldb] Database Cleanup...
[sqldb] Database Cleanup complete!
WARNING:waitress.queue:Task queue depth is 43
WARNING:waitress.queue:Task queue depth is 44
WARNING:waitress.queue:Task queue depth is 45
WARNING:waitress.queue:Task queue depth is 46
WARNING:waitress.queue:Task queue depth is 47
WARNING:waitress.queue:Task queue depth is 48
WARNING:waitress.queue:Task queue depth is 49
WARNING:waitress.queue:Task queue depth is 50
WARNING:waitress.queue:Task queue depth is 51
WARNING:waitress.queue:Task queue depth is 52
WARNING:waitress.queue:Task queue depth is 53
WARNING:waitress.queue:Task queue depth is 54
WARNING:waitress.queue:Task queue depth is 55
```

After a reboot, I am getting the following exception;

```
Traceback (most recent call last):
File "/usr/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/lib/python3.9/site-packages/nimrodel/_api.py", line 160, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/lib/python3.9/site-packages/maloja/apis/native_v1.py", line 84, in get_scrobbles_external
offset = (k_amount.get('page') * k_amount.get('perpage')) if k_amount.get('perpage') is not math.inf else 0
NameError: name 'math' is not defined
```

Another reboot and all seems well, all migrated, speedy and all graphics loaded 👍🏻 looks great!

**Comment by krateng** [comment]
The missing import is fixed, and the GUI rebuilding initially is just a browser issue I think. The task queue should usually not be this big, but could just be that it needs to load all the images the first time. Did the warning reappear since then?

**Comment by mannp** [comment]
Okay, but yes it is still happening...there were 38 warnings in the last hour or so, but only pasted 10.

```
[images] Downloaded https://lastfm.freetls.fastly.net/i/u/300x300/5349b2276d194afe0bd4291aafac88bc.png for local caching
[thirdparty] Could not get track image for (['Passenger'], 'Let Her Go (Recorded at Deezer, Sao Paulo)') from Spotify
Traceback (most recent call last):
File "/usr/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/lib/python3.9/site-packages/nimrodel/_api.py", line 160, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/lib/python3.9/site-packages/maloja/apis/native_v1.py", line 84, in get_scrobbles_external
offset = (k_amount.get('page') * k_amount.get('perpage')) if k_amount.get('perpage') is not math.inf else 0
NameError: name 'math' is not defined
Traceback (most recent call last):
File "/usr/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/lib/python3.9/site-packages/nimrodel/_api.py", line 160, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/lib/python3.9/site-packages/maloja/apis/native_v1.py", line 84, in get_scrobbles_external
offset = (k_amount.get('page') * k_amount.get('perpage')) if k_amount.get('perpage') is not math.inf else 0
NameError: name 'math' is not defined
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 3
WARNING:waitress.queue:Task queue depth is 4
WARNING:waitress.queue:Task queue depth is 5
WARNING:waitress.queue:Task queue depth is 6
WARNING:waitress.queue:Task queue depth is 7
WARNING:waitress.queue:Task queue depth is 8
WARNING:waitress.queue:Task queue depth is 9
WARNING:waitress.queue:Task queue depth is 10
```

**Comment by krateng** [comment]
Are you just normally visiting your web interface? The fact that this error happens implies that something is also hitting your API which could also lead to the task queue issue. Do you run multi-scrobbler or anything else that interacts with Maloja?

**Comment by mannp** [comment]
I am just visiting the root of the instance normally yes, but yes I do run multiscobbler too.

**Comment by krateng** [comment]
Huh, that is very strange. As long as the page doesn't slow down, it shouldn't actually be a problem, but I'm curious where all those requests come from. Can you disable multi-scrobbler for a few minutes and see how high the task queue number goes then?

**Comment by mannp** [comment]
Yes, sure, I have had to delete the ms docker as it wouldn't start for some reason.

Upped a bug issue to ms repo, as an aside, while rebuilding its docker.

I will keep it off for a while, but note I have not seen these waitress errors before v3 and no error in ms working with my v2 maloja instance.

**Comment by krateng** [comment]
Yeah, the error is due to the missing import above, I'm just wondering if that leads to any request spam or something. Might be that alone takes care of it.

**Comment by mannp** [comment]
45 now, without ms and the web page is constantly updating in the browser... i.e. always reloading in Firefox.

Things 'look' okay on the maloja page, just won't stop reloading, with nothing else in the log beyond the 45 warnings.

**Comment by mannp** [comment]
Nothing has changed at mind end since v2, except the import of a few hours of lastfm scrobbles.

The web page has stopped updating now...is it possible it's just taking a lot longer now to populate all the data on the screen in the background?

I will leave it for now and monitor it.

**Comment by krateng** [comment]
The page shouldn't do any XHTTP requests, so once it's loaded, it's fully loaded - it should definitely not randomly decide to reload itself. The only thing that changed in that regard in v3 is image handling - images are now often returned as 307 redirects. Is your browser fully up to date?

**Comment by mannp** [comment]
Restarted the docker this morning, and it crashed....

```
WARNING:waitress.queue:Task queue depth is 54
WARNING:waitress.queue:Task queue depth is 55
WARNING:waitress.queue:Task queue depth is 56
Exception in thread Thread-11:
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1015, in _commit_impl
self.engine.dialect.do_commit(self.connection)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 685, in do_commit
dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 390, in start_db
associated.load_associated_rules()
File "/usr/lib/python3.9/site-packages/maloja/database/associated.py", line 18, in load_associated_rules
conn.execute(op)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3019, in __exit__
self.transaction.__exit__(type_, value, traceback)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/util.py", line 237, in __exit__
self.rollback()
File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
compat.raise_(
File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/util.py", line 233, in __exit__
self.commit()
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2378, in commit
self._do_commit()
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2568, in _do_commit
self._connection_commit_impl()
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2539, in _connection_commit_impl
self.connection._commit_impl()
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1017, in _commit_impl
self._handle_dbapi_exception(e, None, None, None, None)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
util.raise_(
File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1015, in _commit_impl
self.engine.dialect.do_commit(self.connection)
File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 685, in do_commit
dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Another restart and;

```
WARNING:waitress.queue:Task queue depth is 25
WARNING:waitress.queue:Task queue depth is 26
WARNING:waitress.queue:Task queue depth is 27
WARNING:waitress.queue:Task queue depth is 28
```

But the GUI refreshing appears to have stopped and all is well again now ....

**Comment by krateng** [comment]
Very strange. If you run 3.0.2, you can now enable multi-scrobbler again, but I still don't know where all these requests are coming from. Are you getting these warnings only while the page is open in your browser?

**Comment by mannp** [comment]
I have not touched it today, the base URL is always in my browser, but I have not interacted with it today, but this appeared in the logs, just checking them now....

```
WARNING:waitress.queue:Task queue depth is 28
Traceback (most recent call last):
File "/usr/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/lib/python3.9/site-packages/nimrodel/_api.py", line 160, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/lib/python3.9/site-packages/maloja/apis/native_v1.py", line 84, in get_scrobbles_external
offset = (k_amount.get('page') * k_amount.get('perpage')) if k_amount.get('perpage') is not math.inf else 0
NameError: name 'math' is not defined
```

**Comment by krateng** [comment]
Can you check it without the website loaded in your browser at all for a few minutes?

**Comment by mannp** [comment]
O, I was hardcoded on 3.01 and the above error seems to be from multiscrobbler which in turn borked it too.

After updating to 3.0.2 nothing logged for maloja and ms is happy too.

Will monitor for a bit, but might be sorted, although I not at all sure why.

**Comment by FoxxMD** [comment]
@mannp ms dev here, i've pushed a change to MS to fix scrobbling on maloja >= 3.0.0 -- please upgrade your MS docker image to the newest `latest` or `develop` tag, if you haven't already :)

**Comment by mannp** [comment]
> @mannp ms dev here, i've pushed a change to MS to fix scrobbling on maloja >= 3.0.0 -- please upgrade your MS docker image to the newest `latest` or `develop` tag, if you haven't already :)

Thanks, I should have said in my last post, that I was using ms latest, at that point, which solved my current ms issues (except plex lol) 👍🏻
